import { Activity, TrendingUp, Brain, BarChart3 } from 'lucide-react';

export default function AboutPage() {
  return (
    <div className="max-w-3xl mx-auto page-content animate-fade-in">
      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 rounded-xl bg-brand-muted flex items-center justify-center">
          <Activity className="w-5 h-5 text-brand" />
        </div>
        <div>
          <h1 className="text-2xl font-bold text-surface-white">About PulseTrends</h1>
          <p className="text-[13px] text-surface-600">IPO & Crypto Intelligence Platform</p>
        </div>
      </div>
      <p>PulseTrends is a cutting-edge financial intelligence platform that delivers AI-powered analysis of initial public offerings (IPOs), cryptocurrency airdrops, and market-moving news. Our mission is to transform chaotic market signals into clear, actionable insights for modern investors.</p>

      <h2>Our Mission</h2>
      <p>In today's fast-paced markets, information overload is the biggest challenge investors face. PulseTrends was built to solve this — by aggregating data from multiple sources, applying proprietary AI analysis, and presenting clear verdicts that cut through the noise. We believe every investor deserves access to institutional-grade analysis without the institutional price tag.</p>

      <h2>What We Offer</h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 my-4">
        {[
          { icon: TrendingUp, title: 'IPO Intelligence', desc: 'Deep-dive analysis of upcoming IPOs with company overviews, financial snapshots, AI-powered scoring, and risk assessment across six dimensions.' },
          { icon: Activity, title: 'Airdrop Radar', desc: 'Comprehensive tracking of crypto airdrops with eligibility guides, estimated values, farming strategies, and conviction scores.' },
          { icon: Brain, title: 'AI News Analysis', desc: 'Market-moving crypto news with sentiment analysis, impact scoring, and actionable trading insights generated by AI.' },
          { icon: BarChart3, title: 'Risk Metrics', desc: 'Proprietary risk assessment models analysing 24+ metrics across financial health, market conditions, and technical indicators.' },
        ].map(f => (
          <div key={f.title} className="bg-surface-100 border border-surface-300/60 rounded-lg p-4">
            <f.icon className="w-5 h-5 text-brand mb-2" />
            <h3 className="text-[14px] font-semibold text-surface-white mb-1">{f.title}</h3>
            <p className="text-[13px] text-surface-700 leading-relaxed">{f.desc}</p>
          </div>
        ))}
      </div>

      <h2>Our Technology</h2>
      <p>PulseTrends leverages a multi-model AI architecture powered by OpenRouter, NVIDIA, and Google Gemini APIs. Our analysis pipeline processes data from financial filings, on-chain metrics, market feeds, and social signals to generate proprietary scoring. Each analysis undergoes cross-validation across multiple AI models to ensure consistency and accuracy.</p>

      <h2>Our Team</h2>
      <p>PulseTrends is built by a team of financial analysts, data scientists, and software engineers who share a passion for democratising access to quality financial intelligence. We combine decades of experience in investment banking, quantitative analysis, and machine learning to deliver a platform that truly understands what matters to investors.</p>

      <h2>Disclaimer</h2>
      <p>PulseTrends provides informational content and AI-generated analysis for educational purposes only. We are not a registered investment advisor, and nothing on this platform constitutes financial advice. Always conduct your own research and consult with a qualified financial professional before making investment decisions.</p>
    </div>
  );
}
