import { FileText } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto page-content animate-fade-in">
      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 rounded-xl bg-brand-muted flex items-center justify-center">
          <FileText className="w-5 h-5 text-brand" />
        </div>
        <div>
          <h1 className="text-2xl font-bold text-surface-white">Terms of Service</h1>
          <p className="text-[13px] text-surface-600">Last updated: 2 June 2026</p>
        </div>
      </div>

      <h2>Acceptance of Terms</h2>
      <p>By accessing or using PulseTrends ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Platform.</p>

      <h2>Description of Service</h2>
      <p>PulseTrends provides AI-generated analysis and information about IPOs, cryptocurrencies, airdrops, and market news. The Platform is for informational and educational purposes only and does not constitute financial advice.</p>

      <h2>No Investment Advice</h2>
      <p>All content on PulseTrends is generated by artificial intelligence and automated systems. We are not registered investment advisors. Nothing on this Platform should be construed as a recommendation to buy, sell, or hold any security or cryptocurrency. Always conduct your own due diligence and consult with a qualified financial professional.</p>

      <h2>Intellectual Property</h2>
      <p>All content, analysis, scoring models, and data presentations on PulseTrends are the intellectual property of PulseTrends. You may not reproduce, distribute, or create derivative works without our express written consent.</p>

      <h2>User Conduct</h2>
      <p>You agree not to: (a) use the Platform for any unlawful purpose; (b) attempt to gain unauthorised access to our systems; (c) interfere with the proper functioning of the Platform; (d) scrape, crawl, or harvest data without permission.</p>

      <h2>Disclaimer of Warranties</h2>
      <p>The Platform is provided "as is" without any warranties, express or implied. We do not guarantee the accuracy, completeness, or timeliness of the information provided. AI-generated content may contain errors or inaccuracies.</p>

      <h2>Limitation of Liability</h2>
      <p>PulseTrends shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Platform, including but not limited to financial losses from investment decisions.</p>

      <h2>Changes to Terms</h2>
      <p>We reserve the right to modify these terms at any time. Continued use of the Platform after changes constitutes acceptance of the new terms.</p>

      <h2>Governing Law</h2>
      <p>These terms shall be governed by and construed in accordance with the laws of India.</p>

      <h2>Contact</h2>
      <p>For questions about these Terms, contact us at legal@pulsetrends.in.</p>
    </div>
  );
}
